# Generated by Django 4.2.7 on 2026-03-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(help_text='The raw input provided by the user')),
                ('prediction', models.CharField(help_text='Spam/Not Spam or Malicious/Safe', max_length=50)),
                ('confidence', models.FloatField(help_text='Confidence score (0.0 - 1.0)')),
                ('type', models.CharField(choices=[('SMS', 'SMS'), ('URL', 'URL')], help_text='SMS or URL', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prediction Log',
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
